/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio2;

import java.awt.Color;
import java.awt.GridLayout;
import javax.swing.JLabel;

/**
 *
 * @author Vespertino
 */
public class Gui extends javax.swing.JFrame {
    private JLabel[] listaContadores;

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelCenter = new javax.swing.JPanel();
        jPanelSur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtNumeroDeContadores = new javax.swing.JTextField();
        jButtonGo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelCenter.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jPanelSur.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setText("Numero De Contadores");
        jPanelSur.add(jLabel1);

        jtxtNumeroDeContadores.setText("100");
        jPanelSur.add(jtxtNumeroDeContadores);

        jButtonGo.setText("Go!");
        jButtonGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGoActionPerformed(evt);
            }
        });
        jPanelSur.add(jButtonGo);

        jPanel1.add(jPanelSur, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGoActionPerformed
        int nh = Integer.parseInt(jtxtNumeroDeContadores.getText());
        listaContadores = new JLabel[nh];
        int aux;
        
        aux= (int)Math.sqrt(nh);
        GridLayout gl = new GridLayout(aux,aux);
        jPanelCenter.setLayout(gl);
        
        for (int i = 0; i < nh; i++) {
            Contador c = new Contador(this, i);
            Thread t = new Thread(c);
            t.start();
            listaContadores[i] = new JLabel("0");  
            jPanelCenter.add(listaContadores[i]);
            
            
        }
        pack();
    }//GEN-LAST:event_jButtonGoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelSur;
    private javax.swing.JTextField jtxtNumeroDeContadores;
    // End of variables declaration//GEN-END:variables

    public void ponValorContador(int i, int indice) {
        int old;
        
        old = Integer.parseInt(listaContadores[indice].getText());
        old++;
        listaContadores[indice].setText(old+"");
    }

    public void cambiaColor(int indice) {
        listaContadores[indice].setBackground(Color.RED);
        listaContadores[indice].setOpaque(true);
    }
}
