/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio1;

import java.awt.Color;
import javax.swing.DefaultListModel;

/**
 *
 * @author ProfVespertino
 */
public class Gui extends javax.swing.JFrame {

    private Thread t1, t2, t3, t4;

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        t1 = new Thread(new Animal(this, 5000, "Tortuga", 1));
        t2 = new Thread(new Animal(this, 1000, "Guepardo", 2));
        t3 = new Thread(new Animal(this, 3000, "Caballo", 3));
        t4 = new Thread(new Animal(this, 2000, "Liebre", 4));
        // Establecemos el modelo de cada JList
        jList1.setModel(new DefaultListModel<String>());
        jList2.setModel(new DefaultListModel<String>());
        jList3.setModel(new DefaultListModel<String>());
        jList4.setModel(new DefaultListModel<String>());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jPanelSur = new javax.swing.JPanel();
        jButtonArrancar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanelCenter.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jScrollPane1.setViewportView(jList1);

        jPanelCenter.add(jScrollPane1);

        jScrollPane2.setViewportView(jList2);

        jPanelCenter.add(jScrollPane2);

        jScrollPane3.setViewportView(jList3);

        jPanelCenter.add(jScrollPane3);

        jScrollPane4.setViewportView(jList4);

        jPanelCenter.add(jScrollPane4);

        jPanel1.add(jPanelCenter, java.awt.BorderLayout.CENTER);

        jButtonArrancar.setText("Arrancar");
        jButtonArrancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArrancarActionPerformed(evt);
            }
        });
        jPanelSur.add(jButtonArrancar);

        jPanel1.add(jPanelSur, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonArrancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArrancarActionPerformed
        t1.start();
        t2.start();
        t3.start();
        t4.start();
    }//GEN-LAST:event_jButtonArrancarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArrancar;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JPanel jPanelSur;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

    public void setMensaje(int num, String msg) {
        switch (num) {
            case 1:
                ((DefaultListModel) (jList1.getModel())).addElement(msg);
                break;
            case 2:
                ((DefaultListModel) (jList2.getModel())).addElement(msg);
                break;
            case 3:
                ((DefaultListModel) (jList3.getModel())).addElement(msg);
                break;
            case 4:
                ((DefaultListModel) (jList4.getModel())).addElement(msg);
        }
    }

    public void estableceVencedor(int num) {
         switch (num) {
            case 1:
                jList1.setBackground(Color.red);
                break;
            case 2:
                jList2.setBackground(Color.red);
                break;
            case 3:
                jList3.setBackground(Color.red);
                break;
            case 4:
                jList4.setBackground(Color.red);
        }
    }
}
