/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio4;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Vespertino
 */
public class Gui extends javax.swing.JFrame {
    
    private Thread hilo;
    private Contador contador;
    private static int anterior;
    private boolean estaParado;
    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        hilo = new Thread(contador = new Contador(this));
        estaParado = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbStart = new javax.swing.JButton();
        jbRestart = new javax.swing.JButton();
        jbStop = new javax.swing.JButton();
        jbSleep = new javax.swing.JButton();
        jbPriority = new javax.swing.JButton();
        jbIsAlive = new javax.swing.JButton();
        txtTiempoDormir = new javax.swing.JTextField();
        spnPrioridad = new javax.swing.JSpinner();
        jpContador = new javax.swing.JPanel();
        jlHilo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interactuar con hilos");
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        jbStart.setText("START");
        jbStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStartActionPerformed(evt);
            }
        });

        jbRestart.setText("RESTART");
        jbRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRestartActionPerformed(evt);
            }
        });

        jbStop.setText("STOP");
        jbStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStopActionPerformed(evt);
            }
        });

        jbSleep.setText("SLEEP");
        jbSleep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSleepActionPerformed(evt);
            }
        });

        jbPriority.setText("PRIORITY");
        jbPriority.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPriorityActionPerformed(evt);
            }
        });

        jbIsAlive.setText("IS ALIVE");
        jbIsAlive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIsAliveActionPerformed(evt);
            }
        });

        jlHilo.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jlHilo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHilo.setText("0");

        javax.swing.GroupLayout jpContadorLayout = new javax.swing.GroupLayout(jpContador);
        jpContador.setLayout(jpContadorLayout);
        jpContadorLayout.setHorizontalGroup(
            jpContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContadorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlHilo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jpContadorLayout.setVerticalGroup(
            jpContadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpContadorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlHilo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jpContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbPriority, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbRestart, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(jbSleep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbIsAlive, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTiempoDormir)
                            .addComponent(spnPrioridad))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbStop)
                                    .addComponent(jbStart))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbIsAlive))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jbRestart)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbSleep)
                            .addComponent(txtTiempoDormir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbPriority)
                            .addComponent(spnPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpContador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jbStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStartActionPerformed
        //boton start
        
        try {
            hilo.start();
        } catch (IllegalThreadStateException e) {
        }
        
    }//GEN-LAST:event_jbStartActionPerformed

    private void jbRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRestartActionPerformed
        contador.getLabel().setText(anterior+"");
        contador.setC(0);
        contador.setI(anterior);
        estaParado=false;
    }//GEN-LAST:event_jbRestartActionPerformed

    private void jbSleepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSleepActionPerformed
        long millis = Long.parseLong(txtTiempoDormir.getText());
        try {
            contador.getLabel().setText(anterior+"");
            hilo.sleep(millis);
            
        } catch (InterruptedException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbSleepActionPerformed

    private void jbPriorityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPriorityActionPerformed
       int prio = Integer.parseInt(spnPrioridad.getValue().toString());
       hilo.setPriority(prio);
    }//GEN-LAST:event_jbPriorityActionPerformed

    private void jbStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStopActionPerformed
        estaParado = false;
        parate();
        //contador.setC(0);
    }//GEN-LAST:event_jbStopActionPerformed

    private void jbIsAliveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIsAliveActionPerformed
        boolean estaVivo = hilo.isAlive();
        if (estaVivo || !estaParado) {
            JOptionPane.showMessageDialog(null, "Estoy activo :)");
        }else{
            if (!estaParado) {
                JOptionPane.showMessageDialog(null, "Estoy muerto :(");
            }
            
        }
    }//GEN-LAST:event_jbIsAliveActionPerformed

    //generarme un getter del label
    
    public JLabel getJlHilo() {
        return jlHilo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbIsAlive;
    private javax.swing.JButton jbPriority;
    private javax.swing.JButton jbRestart;
    private javax.swing.JButton jbSleep;
    private javax.swing.JButton jbStart;
    private javax.swing.JButton jbStop;
    private javax.swing.JLabel jlHilo;
    private javax.swing.JPanel jpContador;
    private javax.swing.JSpinner spnPrioridad;
    private javax.swing.JTextField txtTiempoDormir;
    // End of variables declaration//GEN-END:variables

    private void parate() {
        estaParado = false;
        anterior = Integer.parseInt(jlHilo.getText());
        int numero = Integer.parseInt(jlHilo.getText());
        contador.setI(numero);
        contador.setC(-1);
    }
}
